// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJvjiWOBUhVouuh5FvJH65qe_Pq_GAS68',
    appId: '1:687070457802:web:790237f91df22fbada2933',
    messagingSenderId: '687070457802',
    projectId: 'tottracker-238bb',
    authDomain: 'tottracker-238bb.firebaseapp.com',
    storageBucket: 'tottracker-238bb.appspot.com',
    measurementId: 'G-EMDL52TEXK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0sbpOvoRNPReM4mHE8af1PSZ_8FzLvxk',
    appId: '1:687070457802:android:deca24120fddedc2da2933',
    messagingSenderId: '687070457802',
    projectId: 'tottracker-238bb',
    storageBucket: 'tottracker-238bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3mlXbkvPyRsRX29_ltSMK_zJ7SWciL2M',
    appId: '1:687070457802:ios:2c97cf927374c60ada2933',
    messagingSenderId: '687070457802',
    projectId: 'tottracker-238bb',
    storageBucket: 'tottracker-238bb.appspot.com',
    iosClientId: '687070457802-mhe78p74716hlg72pddobchte27t87jr.apps.googleusercontent.com',
    iosBundleId: 'com.example.tottracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3mlXbkvPyRsRX29_ltSMK_zJ7SWciL2M',
    appId: '1:687070457802:ios:2c97cf927374c60ada2933',
    messagingSenderId: '687070457802',
    projectId: 'tottracker-238bb',
    storageBucket: 'tottracker-238bb.appspot.com',
    iosClientId: '687070457802-mhe78p74716hlg72pddobchte27t87jr.apps.googleusercontent.com',
    iosBundleId: 'com.example.tottracker',
  );
}
